#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "context-simulator.fullname" . }}
  labels:
    {{- include "context-simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8281
      protocol: TCP
      name: enm1
    - port: 8282
      protocol: TCP
      name: enm2
    - port: 8280
      protocol: TCP
      name: cs

  selector:
    {{- include "context-simulator.selectorLabels" . | nindent 4 }}
