#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-oss-adc-ems-notification-collector.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "eric-oss-adc-ems-notification-collector.name" . }}
    helm.sh/chart: {{ template "eric-oss-adc-ems-notification-collector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ template "eric-oss-adc-ems-notification-collector.version" . }}
  annotations:
  {{- include "eric-oss-adc-ems-notification-collector.product-info" . | indent 4 }}
  {{- include "eric-oss-adc-ems-notification-collector.config-annotations" . | indent 4 }}
spec:
  minAvailable: {{ template "eric-oss-adc-ems-notification-collector.pod-disruption-budget" . }}
  selector:
    matchLabels:
      app: {{ template "eric-oss-adc-ems-notification-collector.name" . }}